mex normals_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_features

%%
mex segment_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_segmentation