mex normals_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_features
disp('Done')
%%
mex normals_integral_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_features
disp('Done')
%[T, P] = normals_integral_mex(cloud.xyz, 'cov', 2, 0.0);
%%
mex segment_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_segmentation
disp('Done')

%%
mex segment_prism_mex.cpp ...
    -I/usr/local/include/pcl-1.7/ ...
    -I/usr/include ...
    -I/usr/local/include/eigen3/ ...
    -I/opt/local/include/ ...
    -L/usr/local/lib/ ...
    -lpcl_search -lpcl_kdtree -lpcl_common -lpcl_segmentation -lpcl_filters -lpcl_surface -lqhull
disp('Done')